apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: infomaniak-api-token-captaindartz-org
    namespace: external-dns
spec:
    secrets:
        - name: infomaniak-api-token-captaindartz-org
          stringData:
            api-token: ENC[AES256_GCM,data:ZPuah3kfgqFfznYjlVugxd9N4wVHzmhaAi5gngARrCA5YPP2N5k7DLyfmM+LtowtRziQIk+CE7i4a4dQMHEYUmF7yZ1FcthruOsTVBPHdDk=,iv:dmCZJg4gWDTeW3N+ga9gTCIZPHSgpPZSHn8JFna/nR4=,tag:8vOj/M9fyJnFlEkdoSiiXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUenJSN0ErbngydlNVRHVF
            cWhiZjZKejNmb1NuQ3RJZEFCSXNDNFBBMkZZCjdJSXBhWXJLeVdCYWpZdFR4elZp
            cTVTeUZnM2NGL3dZZU5vM1F4WHpObFEKLS0tIG5QekF4ajEwcEpUQUF1SnpUeHlx
            aWdWTE9yL2YvU25SYVJEdjVjZDB1TUEKNHrSi9O3b1Wq9AhGqLRoiyWUIhHoqSDG
            mOZ5DbKjUI6CyPvQMLlLQ8Cz1k0PETfcjYGVlng/72INDgoywQrnRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:46:11Z"
    mac: ENC[AES256_GCM,data:6nm72nA0iMloLfwn9YSwhYgMSy7Gokkl+6TvRPVTOpFDSQF/db8/hzpDkxnB/W4S3t/bzQ/EGDreQeLXGf7tB0dOq33CHNJAL7sLNPjzyahoP7ura/w1KiDMtUZuICH2z8u4S4q3yLI0SSV0gPj3+GYRzCzWRlYnouIV+gUqfm0=,iv:11CktGt3kVb1a7qYycehZpAsLlrIlWWlUpXZvZrcSWw=,tag:g3TJ5Cz/CU57ccRgBLIu8g==,type:str]
    version: 3.13.3
