apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: infomaniak-api-token-cluster-domain
    namespace: external-dns
spec:
    secrets:
        - name: infomaniak-api-token-cluster-domain
          stringData:
            api-token: ENC[AES256_GCM,data:ZPuah3kfgqFfznYjlVugxd9N4wVHzmhaAi5gngARrCA5YPP2N5k7DLyfmM+LtowtRziQIk+CE7i4a4dQMHEYUmF7yZ1FcthruOsTVBPHdDk=,iv:dmCZJg4gWDTeW3N+ga9gTCIZPHSgpPZSHn8JFna/nR4=,tag:8vOj/M9fyJnFlEkdoSiiXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUenJSN0ErbngydlNVRHVF
            cWhiZjZKejNmb1NuQ3RJZEFCSXNDNFBBMkZZCjdJSXBhWXJLeVdCYWpZdFR4elZp
            cTVTeUZnM2NGL3dZZU5vM1F4WHpObFEKLS0tIG5QekF4ajEwcEpUQUF1SnpUeHlx
            aWdWTE9yL2YvU25SYVJEdjVjZDB1TUEKNHrSi9O3b1Wq9AhGqLRoiyWUIhHoqSDG
            mOZ5DbKjUI6CyPvQMLlLQ8Cz1k0PETfcjYGVlng/72INDgoywQrnRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T19:13:15Z"
    mac: ENC[AES256_GCM,data:YWg3S0wVzl7Y7uEe1ucZiMg+1RYR4KO0g+foTRVDg/FyFeVBRq82DlIy3aDiyW/PANdDOKcY0Dh/KuO7p97V5kWHQ5CpH4L1Le/CnGp2mJPhiFhHg45zsNuNTvEf3ai6VgxyOE3HUyTdtqMMeURXgy1pxU1KnwBdkXZ1gB/wZuo=,iv:/0q/+Jns5uLqXxacflKDBg/pHH+pVBkrfNKLuIH9Qkc=,tag:t4tuw1G3L6NE068u6gJT7w==,type:str]
    version: 3.13.3
