provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/m0nsterrr/external-dns-webhook-infomaniak
      tag: v0.1.3
    env:
      - name: INFOMANIAK_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: infomaniak-api-token-cluster-domain
            key: api-token
domainFilters:
  - $(DOMAIN_NAME)
policy: sync
txtOwnerId: external-dns-infomaniak
sources:
  - ingress
  - service
extraArgs:
  - --default-targets=ip.$(DOMAIN_NAME)
  - --force-default-targets
registry: txt
logLevel: info
