apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: loki-
resources:
  - ../../../components/volume-snapshotter
patches:
  - target:
      kind: CronJob
      name: snapshotter
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: snapshotter
      spec:
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: snapshotter
                    env:
                      - name: SNAP_PREFIX
                        value: "loki"
                      - name: SNAP_PVC
                        value: "storage-loki-0"
                      - name: SNAP_RETENTION
                        value: "7"
