---
# handlers file for traefik

- name: Restart Traefik service
  ansible.builtin.shell: |
    XDG_RUNTIME_DIR=/run/user/$(id -u) systemctl --user restart traefik.service
  become: true
  become_user: "{{ service_user_name }}"
  changed_when: true
  when: traefik_enabled | default(true) | bool
