---
# handlers file for openbao
- name: Restart OpenBao service
  ansible.builtin.systemd_service:
    name: openbao.service
    scope: user
    state: restarted
    daemon_reload: true
  become: true
  become_user: "{{ service_user_name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ openbao_service_uid.stdout | default('1001') }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ openbao_service_uid.stdout | default('1001') }}/bus"
