apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi-operator-system
spec:
    secrets:
        - name: csi-rbd-secret
          stringData:
            userID: ENC[AES256_GCM,data:4zOezK02UbGpzL3+,iv:WBVAUk6nZ3Gpcq7m1/tYSvxkBKu371GA2Avw10r1an4=,tag:dA4zrl1uzB3TaaZxAK01Mw==,type:str]
            userKey: ENC[AES256_GCM,data:VjAk6mNzxuRPyDsws79q+1HWF6NCyWCJ1QrD8GjOGgQEQ4U81ncefg==,iv:Wq97YEFdjQujadLWnlpTyQDPlurjc7gDtqfnLiz30j8=,tag:w+NA9x7BWUQGUJQkRiDQYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaWFEeDhLdGtCeGhQR3g0
            WGloc2YrT3hiY2h1RW5TaWV5QXJHbGxhSURvCjdmaWhzamVQSXRKb25CTWQ0eGht
            SzNKUkswSm4vRUtJTUovbXFjaStJL1EKLS0tIFdYN282SHptRWlLaTQxZWNxSWZH
            MEptOVo4QU5UNWpoWm90VFU2aUlkS0EK0hl/yrENl8h5teQBnJPCpfNSDIzdRpVE
            8hxTitGRGp6j68exHapam97prJlHG517GZOQpoDE/d8HZ2XbIc2bZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:18:59Z"
    mac: ENC[AES256_GCM,data:oUxeJRxM+nqJz/dr+vDOKesBECl4AHYMDEN0Ec0YjfQi5ryZukHVVAcO+2lFzi1daWoKFQq7cO18xwWxn0o7+/eg8Y7I9gs36ouwED+GCZlgHC6b0KiSpFVVS5/iq7ZI1q8qPCkxR96ZeY+tiOgSThKP9pIcZmatVw3sIqBcJbQ=,iv:Rj2CMw3IszI2snAmIc7firRcu8GhBrbzlVHnXqWAkB8=,tag:6U+nNDwhjhgBuCfYhdVqfA==,type:str]
    version: 3.13.3
---
apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi-operator-system
spec:
    secrets:
        - name: csi-cephfs-secret
          stringData:
            userID: ENC[AES256_GCM,data:Gnmfb+Dj2Oisy07K,iv:PQblfYq/oMKLgEvHbEz+PVIc4HI/SP+bJKnd5w8/p8w=,tag:LFfreLyE9f8ByPLu6fG2pA==,type:str]
            userKey: ENC[AES256_GCM,data:AZlWcl7Ft0UOAumFLi1CMWi0gMKY6KjhHbZ7fuk5fJfe9xXIT267rw==,iv:a0qg8t+nuOT12ax0JcVt8nLEBxRqAIoAy7nvL8UXo+c=,tag:17TjD1j8ouS+YhnK/6eafw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaWFEeDhLdGtCeGhQR3g0
            WGloc2YrT3hiY2h1RW5TaWV5QXJHbGxhSURvCjdmaWhzamVQSXRKb25CTWQ0eGht
            SzNKUkswSm4vRUtJTUovbXFjaStJL1EKLS0tIFdYN282SHptRWlLaTQxZWNxSWZH
            MEptOVo4QU5UNWpoWm90VFU2aUlkS0EK0hl/yrENl8h5teQBnJPCpfNSDIzdRpVE
            8hxTitGRGp6j68exHapam97prJlHG517GZOQpoDE/d8HZ2XbIc2bZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:18:59Z"
    mac: ENC[AES256_GCM,data:oUxeJRxM+nqJz/dr+vDOKesBECl4AHYMDEN0Ec0YjfQi5ryZukHVVAcO+2lFzi1daWoKFQq7cO18xwWxn0o7+/eg8Y7I9gs36ouwED+GCZlgHC6b0KiSpFVVS5/iq7ZI1q8qPCkxR96ZeY+tiOgSThKP9pIcZmatVw3sIqBcJbQ=,iv:Rj2CMw3IszI2snAmIc7firRcu8GhBrbzlVHnXqWAkB8=,tag:6U+nNDwhjhgBuCfYhdVqfA==,type:str]
    version: 3.13.3
