apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "proxmox-rbd"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "storage"
  pool: "pool1_ssd"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-operator-system
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "proxmox-rbd-delete"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "storage"
  pool: "pool1_ssd"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-operator-system
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - discard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "proxmox-cephfs"
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "storage"
  fsName: "cephfs1_ssd"
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-operator-system
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "proxmox-cephfs-delete"
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "storage"
  fsName: "cephfs1_ssd"
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-operator-system
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-operator-system
reclaimPolicy: Delete
allowVolumeExpansion: true
