apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: cloudflare-api-token-main
    namespace: cert-manager
spec:
    secrets:
        - name: cloudflare-api-token-main
          stringData:
            token: ENC[AES256_GCM,data:UnrAHAD9UwQ=,iv:8FloEX120ShkYn+ta2CJfilMzleoBvIlzT7f9rxN5i0=,tag:e0OhH7r/T7KpTm8/AcUwCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySlFkMTM4K1p5bGt3MnFp
            cWthWkZCNDg5NWcxNDZpYitPQWoyd0lCRlJnClRUUzdHU0VsVmZTSVNNcG1icWRK
            bVpDWWd3djBSakg4UmhzdzNTTkp5dXcKLS0tIGtsZW93WC9DcVFKVURvaTlKdnYv
            cmh0bW5rNVhISzN4SkUyM1d1YVdaQmMKwY51Kw9qrbvhd4MjRIgSnPqH/wBx7o2M
            JgZzs4lXR6IzQ2Maixxi1RTzwVp/AkaILZN+mE85g1Da8W+VVEtaGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:29:11Z"
    mac: ENC[AES256_GCM,data:3bW3kBctXjZ2P1dQAd75S8yzQK4QG7gcu9GP1Qjy5H9yF72jXOOJ/Eg1VIJxZRVzZfsmjM7q3YQxUQo47fvuUT7Tb17QGECMrfafAFAJFVMpgvPZ20pEAiSsY5GwGMnlj5kklRyRX7lIoCznwq7AlKs9vZoc1qYmCkleHMqzO48=,iv:uykFS/ALMLfzTrUnm/DtgZckVDE78Mow68gXboNSiwM=,tag:wXJ1aiqa1cSskw14lg4yaA==,type:str]
    version: 3.13.3
---
apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: ovh-creds-other
    namespace: cert-manager
spec:
    secrets:
        - name: ovh-creds-other
          stringData:
            applicationKey: ENC[AES256_GCM,data:7FzK0L9q0/8=,iv:WoVEzfxv4y3lRWpKPAyqTPkj9hwEjVspqbRlRwLUv8A=,tag:xL3LDIWEAhVvIV4QzFtwcA==,type:str]
            applicationSecret: ENC[AES256_GCM,data:Q0DmmgClCMs=,iv:017aJqU/YgQ25jtSZ80dzbhHbhBkX3R9FOxECZAJ6TI=,tag:kBC9IY7lirErGdQJgcE6eA==,type:str]
            applicationConsumerKey: ENC[AES256_GCM,data:NzD/GK5z+4Y=,iv:gUYRzbSlHMGALC/orCPXU76MosYGey2XJwf8T1oXqHQ=,tag:vfLsMC5QOHqW1C+FBqWiZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySlFkMTM4K1p5bGt3MnFp
            cWthWkZCNDg5NWcxNDZpYitPQWoyd0lCRlJnClRUUzdHU0VsVmZTSVNNcG1icWRK
            bVpDWWd3djBSakg4UmhzdzNTTkp5dXcKLS0tIGtsZW93WC9DcVFKVURvaTlKdnYv
            cmh0bW5rNVhISzN4SkUyM1d1YVdaQmMKwY51Kw9qrbvhd4MjRIgSnPqH/wBx7o2M
            JgZzs4lXR6IzQ2Maixxi1RTzwVp/AkaILZN+mE85g1Da8W+VVEtaGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:29:11Z"
    mac: ENC[AES256_GCM,data:3bW3kBctXjZ2P1dQAd75S8yzQK4QG7gcu9GP1Qjy5H9yF72jXOOJ/Eg1VIJxZRVzZfsmjM7q3YQxUQo47fvuUT7Tb17QGECMrfafAFAJFVMpgvPZ20pEAiSsY5GwGMnlj5kklRyRX7lIoCznwq7AlKs9vZoc1qYmCkleHMqzO48=,iv:uykFS/ALMLfzTrUnm/DtgZckVDE78Mow68gXboNSiwM=,tag:wXJ1aiqa1cSskw14lg4yaA==,type:str]
    version: 3.13.3
