apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: infomaniak-api-token-captaindartz-org
    namespace: cert-manager
spec:
    secrets:
        - name: infomaniak-api-token-captaindartz-org
          stringData:
            api-token: ENC[AES256_GCM,data:iXY9ektV56NvV7IJlQafL12rxFBg+6EXEQIhubZeV7RgymVSvk1/+Ie8pH2NRJ1TgrTr/25gi5o+ZqLD0WuA1vl2Mn88UF0E9UdknMd5sVQ=,iv:NQfqQDuSDVf+qeK5IM1GAOVjCTy88GhyiGzSqQdZFns=,tag:1mGrCVchrkJmdrpPiT7T/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySlFkMTM4K1p5bGt3MnFp
            cWthWkZCNDg5NWcxNDZpYitPQWoyd0lCRlJnClRUUzdHU0VsVmZTSVNNcG1icWRK
            bVpDWWd3djBSakg4UmhzdzNTTkp5dXcKLS0tIGtsZW93WC9DcVFKVURvaTlKdnYv
            cmh0bW5rNVhISzN4SkUyM1d1YVdaQmMKwY51Kw9qrbvhd4MjRIgSnPqH/wBx7o2M
            JgZzs4lXR6IzQ2Maixxi1RTzwVp/AkaILZN+mE85g1Da8W+VVEtaGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:46:46Z"
    mac: ENC[AES256_GCM,data:PAQ9t7pUDOhtFkf/8ByTmPM1qL6aAmdpqiJuHlEZe7bH9yQvF/aUYcvMlL6Ax1PjYQV/DEufb/LEs5CKgD03T6pJN4O6bB8buGdxmVlLy74vX0os0W3jb9HMS37kGY2if9R7VcIMefy/QKdd8gbYEnd4MXuJcM0/NdIBUBWWVkg=,iv:hh28AL3xfEvDO5UZThtBm2+0fVi406wWF9/mdbc8M20=,tag:lwLaLLr2sgZgZIDzO1R+Bg==,type:str]
    version: 3.13.3
