apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: alertmanager-config
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secrets:
        - name: alertmanager-config
          stringData:
            alertmanager.yaml: ENC[AES256_GCM,data:wsVzyNRdmVSoYv3KzkcLJH2BtbfgemNMiY7KfBcdyi7cLvn0vF+gV6KOpFsA5K7kwbCMBXAtQ2clsbB+8jL1rFCISyjsDRkdMhKupKmLHiYsM1sRY++XRgrnQXtarzlDEoPeT/Xfptqu6U4SxfpdYxR6DrV1mFhzIAf4aai0yEixfQ80XFeqPAE4BgVWxc1+2hBlQ386IRww28Adq4EB5Zj1aMPwR2BgyLGZAry8qLyKNcVBWvSeFA/qY/znnSfYyf7Zj3gMe5UM3kF4D+RWP4ql9IobKDXBxovdA1bG732sNf2CdccmGr2Mqhj2AfPffGL7fGA8fQaWuxXVnrQVTUSniXPqYXKLJe/Ul3Gf8auX7+3nEQg55EgLk694LO1DUgetqErVggCUMelc7JemaCaiK1I7ncrsM57KcZN3yFn1ZQEPYuEMSZmIZp1hRQog1hkDBEZkWvpJ8jrwr6b4JabKFWV/X5z+6/hkrwFJzatAhCdkJZw4Rpiyd9TJF2vy8auKd3LsGqyzyY2NtHXGK0JhadfgIZoggr81CqhoRPMBsWpEBgQDVOSAgE05MWqJ1bZmiZx/yKt64m5GJoTogwrL,iv:5cxLCVI458AUYKShkkEU6Ey0nrxp1x9NBdTIgUQ7VS0=,tag:5wh7Ob1gEaOsBCYyiwETlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eDNCU1FuWkpwTW1iTWdt
            dmhFWnQrcTM3NGFZTTJEcXVSQ1J5eXREeUdNCklkRWtpNW9YdVg0YTVBdy93L0JS
            RzVXb3k0QmN5d1h2YUxZbXFHN2hjZUUKLS0tIE8wUnZyTDNkUXdmbHRLWFhuLzVw
            WkovUEova0dOcW1KbjZzMXNGcis3SjAKemf9OBF1iIomB1pB/eUxf7c2eTmLgZcK
            hWBcyevta8GtXxJCaKF8wOfw99INe/GCujPewKjDnLlSOHkjyClcvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:25:45Z"
    mac: ENC[AES256_GCM,data:cw3cJdH88oLnvVZQAWCEg/qEQrZVfWGPtS2LhO79QW4ilLq2czFXaV+8DeNL/KHNCnqjIWNpTq89xnly8PH7DDPuhEPqnXxkaueJLQFp2rB40r0GTR7aPoYGKVxglEH3EPP/HVyouD99+0T4lAmNpFghjnXHi+EGf6eLksVwa7Y=,iv:j2cPDghpOTs10Y+Zd+Nr0e0KjsdNi8b6xDSAHN/wHoM=,tag:Rjnh3Xl8A2KAaWfrarnWwQ==,type:str]
    version: 3.13.3
