apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secrets:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:sYeXWVE=,iv:pMOB9YSUHYStgFk3Df0hzij3RJ+t1hrhDctti4JtJ8w=,tag:9vVdQmfX4cSyBIwJc6DZyQ==,type:str]
            admin-password: ENC[AES256_GCM,data:Z9sqlG4=,iv:U1Wf5xY/3/b9RWJCSclIDIB5QlwmUATIBguF7hfvlRQ=,tag:kMibVKC3BdKyM1bYFokfCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQUFXRW5RaUg3NTRsQUYx
            MnBuOWFyNGN4ZlVVZVBKMzV6a01XaFNrK0h3CjM0b0tEeWZ4emljWmROcWFzdEJD
            UFdibWVlT0dJSGhCbDJ2YW5aM1pMYlUKLS0tIG42Znpza2JZdWZIQzRpa2JqSlBZ
            dXhhMEhEaCszUXgyeVY2U1F2S3J5ZVEKismPjf1j/BGdJIbPTIEo8R1c4mITow4J
            3K0EfQKaCB0mbLJCpad6+Pm7HeJnWU0qAU9jY/V8Vj+H9R/SHqLBiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12us5969kl4sn4enpyw2lmunjtn4k82srcv952fta8950tyuj4fmql74ayn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T18:56:45Z"
    mac: ENC[AES256_GCM,data:UJSRUXhOpeS5VHAIsYxGEZujM7HgQ4jut8XXr22ccMxRVOW7pDwaEc3w+Nx/rcpuKj4M+mAamL0KHUIjnzQPpxbo/WBAAdm2UzO/l3VS4oedFl3ZfyB/Y3j4pS0WROKpL4qTErzssrF1r0IYE+hWca7pc9HcM9qCtedRiPceaJE=,iv:aERDAGg2JptkGUW8RIajvgk42BQIH/ZbxrvR0j3sY8A=,tag:CFOeLaP6Zy2ocMIL/+AgcQ==,type:str]
    version: 3.13.3
