---
# defaults file for traefik

traefik_enabled: true
traefik_version: "v3"
traefik_http_port: 8000
traefik_https_port: 8443
traefik_cert_validity_days: 10950 # 30 years (10950 days)

# Default domain names (overridden in inventory/group_vars/all.yml)
traefik_forgejo_domain: "git.example.com"
traefik_openbao_domain: "openbao.example.com"
